/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ScannerLazyImport = createFileRoute('/scanner')()
const ColorsLazyImport = createFileRoute('/colors')()

// Create/Update Routes

const ScannerLazyRoute = ScannerLazyImport.update({
  path: '/scanner',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/scanner.lazy').then((d) => d.Route))

const ColorsLazyRoute = ColorsLazyImport.update({
  path: '/colors',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/colors.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsLazyImport
      parentRoute: typeof rootRoute
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ColorsLazyRoute,
  ScannerLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/colors",
        "/scanner"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/colors": {
      "filePath": "colors.lazy.tsx"
    },
    "/scanner": {
      "filePath": "scanner.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
