/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CartImport } from './routes/cart'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as CartServiceImport } from './routes/cart.service'
import { Route as LayoutListImport } from './routes/_layout/list'
import { Route as LayoutFavoritesImport } from './routes/_layout/favorites'
import { Route as LayoutListIdPercentsImport } from './routes/_layout/list.$id.percents'
import { Route as LayoutListIdDetailsImport } from './routes/_layout/list.$id.details'
import { Route as LayoutFavoritesFavoriteIdNotesImport } from './routes/_layout/favorites.$favoriteId.notes'

// Create Virtual Routes

const StatsLazyImport = createFileRoute('/stats')()
const ScannerLazyImport = createFileRoute('/scanner')()
const NotificationsLazyImport = createFileRoute('/notifications')()
const ColorsLazyImport = createFileRoute('/colors')()

// Create/Update Routes

const StatsLazyRoute = StatsLazyImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/stats.lazy').then((d) => d.Route))

const ScannerLazyRoute = ScannerLazyImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/scanner.lazy').then((d) => d.Route))

const NotificationsLazyRoute = NotificationsLazyImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/notifications.lazy').then((d) => d.Route))

const ColorsLazyRoute = ColorsLazyImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/colors.lazy').then((d) => d.Route))

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CartServiceRoute = CartServiceImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => CartRoute,
} as any)

const LayoutListRoute = LayoutListImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFavoritesRoute = LayoutFavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutListIdPercentsRoute = LayoutListIdPercentsImport.update({
  id: '/$id/percents',
  path: '/$id/percents',
  getParentRoute: () => LayoutListRoute,
} as any)

const LayoutListIdDetailsRoute = LayoutListIdDetailsImport.update({
  id: '/$id/details',
  path: '/$id/details',
  getParentRoute: () => LayoutListRoute,
} as any)

const LayoutFavoritesFavoriteIdNotesRoute =
  LayoutFavoritesFavoriteIdNotesImport.update({
    id: '/$favoriteId/notes',
    path: '/$favoriteId/notes',
    getParentRoute: () => LayoutFavoritesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsLazyImport
      parentRoute: typeof rootRoute
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsLazyImport
      parentRoute: typeof rootRoute
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerLazyImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/favorites': {
      id: '/_layout/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof LayoutFavoritesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/list': {
      id: '/_layout/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof LayoutListImport
      parentRoute: typeof LayoutImport
    }
    '/cart/service': {
      id: '/cart/service'
      path: '/service'
      fullPath: '/cart/service'
      preLoaderRoute: typeof CartServiceImport
      parentRoute: typeof CartImport
    }
    '/_layout/favorites/$favoriteId/notes': {
      id: '/_layout/favorites/$favoriteId/notes'
      path: '/$favoriteId/notes'
      fullPath: '/favorites/$favoriteId/notes'
      preLoaderRoute: typeof LayoutFavoritesFavoriteIdNotesImport
      parentRoute: typeof LayoutFavoritesImport
    }
    '/_layout/list/$id/details': {
      id: '/_layout/list/$id/details'
      path: '/$id/details'
      fullPath: '/list/$id/details'
      preLoaderRoute: typeof LayoutListIdDetailsImport
      parentRoute: typeof LayoutListImport
    }
    '/_layout/list/$id/percents': {
      id: '/_layout/list/$id/percents'
      path: '/$id/percents'
      fullPath: '/list/$id/percents'
      preLoaderRoute: typeof LayoutListIdPercentsImport
      parentRoute: typeof LayoutListImport
    }
  }
}

// Create and export the route tree

interface LayoutFavoritesRouteChildren {
  LayoutFavoritesFavoriteIdNotesRoute: typeof LayoutFavoritesFavoriteIdNotesRoute
}

const LayoutFavoritesRouteChildren: LayoutFavoritesRouteChildren = {
  LayoutFavoritesFavoriteIdNotesRoute: LayoutFavoritesFavoriteIdNotesRoute,
}

const LayoutFavoritesRouteWithChildren = LayoutFavoritesRoute._addFileChildren(
  LayoutFavoritesRouteChildren,
)

interface LayoutListRouteChildren {
  LayoutListIdDetailsRoute: typeof LayoutListIdDetailsRoute
  LayoutListIdPercentsRoute: typeof LayoutListIdPercentsRoute
}

const LayoutListRouteChildren: LayoutListRouteChildren = {
  LayoutListIdDetailsRoute: LayoutListIdDetailsRoute,
  LayoutListIdPercentsRoute: LayoutListIdPercentsRoute,
}

const LayoutListRouteWithChildren = LayoutListRoute._addFileChildren(
  LayoutListRouteChildren,
)

interface LayoutRouteChildren {
  LayoutFavoritesRoute: typeof LayoutFavoritesRouteWithChildren
  LayoutListRoute: typeof LayoutListRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutFavoritesRoute: LayoutFavoritesRouteWithChildren,
  LayoutListRoute: LayoutListRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface CartRouteChildren {
  CartServiceRoute: typeof CartServiceRoute
}

const CartRouteChildren: CartRouteChildren = {
  CartServiceRoute: CartServiceRoute,
}

const CartRouteWithChildren = CartRoute._addFileChildren(CartRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/colors': typeof ColorsLazyRoute
  '/notifications': typeof NotificationsLazyRoute
  '/scanner': typeof ScannerLazyRoute
  '/stats': typeof StatsLazyRoute
  '/favorites': typeof LayoutFavoritesRouteWithChildren
  '/list': typeof LayoutListRouteWithChildren
  '/cart/service': typeof CartServiceRoute
  '/favorites/$favoriteId/notes': typeof LayoutFavoritesFavoriteIdNotesRoute
  '/list/$id/details': typeof LayoutListIdDetailsRoute
  '/list/$id/percents': typeof LayoutListIdPercentsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/colors': typeof ColorsLazyRoute
  '/notifications': typeof NotificationsLazyRoute
  '/scanner': typeof ScannerLazyRoute
  '/stats': typeof StatsLazyRoute
  '/favorites': typeof LayoutFavoritesRouteWithChildren
  '/list': typeof LayoutListRouteWithChildren
  '/cart/service': typeof CartServiceRoute
  '/favorites/$favoriteId/notes': typeof LayoutFavoritesFavoriteIdNotesRoute
  '/list/$id/details': typeof LayoutListIdDetailsRoute
  '/list/$id/percents': typeof LayoutListIdPercentsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/colors': typeof ColorsLazyRoute
  '/notifications': typeof NotificationsLazyRoute
  '/scanner': typeof ScannerLazyRoute
  '/stats': typeof StatsLazyRoute
  '/_layout/favorites': typeof LayoutFavoritesRouteWithChildren
  '/_layout/list': typeof LayoutListRouteWithChildren
  '/cart/service': typeof CartServiceRoute
  '/_layout/favorites/$favoriteId/notes': typeof LayoutFavoritesFavoriteIdNotesRoute
  '/_layout/list/$id/details': typeof LayoutListIdDetailsRoute
  '/_layout/list/$id/percents': typeof LayoutListIdPercentsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/cart'
    | '/colors'
    | '/notifications'
    | '/scanner'
    | '/stats'
    | '/favorites'
    | '/list'
    | '/cart/service'
    | '/favorites/$favoriteId/notes'
    | '/list/$id/details'
    | '/list/$id/percents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/cart'
    | '/colors'
    | '/notifications'
    | '/scanner'
    | '/stats'
    | '/favorites'
    | '/list'
    | '/cart/service'
    | '/favorites/$favoriteId/notes'
    | '/list/$id/details'
    | '/list/$id/percents'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/cart'
    | '/colors'
    | '/notifications'
    | '/scanner'
    | '/stats'
    | '/_layout/favorites'
    | '/_layout/list'
    | '/cart/service'
    | '/_layout/favorites/$favoriteId/notes'
    | '/_layout/list/$id/details'
    | '/_layout/list/$id/percents'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  CartRoute: typeof CartRouteWithChildren
  ColorsLazyRoute: typeof ColorsLazyRoute
  NotificationsLazyRoute: typeof NotificationsLazyRoute
  ScannerLazyRoute: typeof ScannerLazyRoute
  StatsLazyRoute: typeof StatsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  CartRoute: CartRouteWithChildren,
  ColorsLazyRoute: ColorsLazyRoute,
  NotificationsLazyRoute: NotificationsLazyRoute,
  ScannerLazyRoute: ScannerLazyRoute,
  StatsLazyRoute: StatsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/cart",
        "/colors",
        "/notifications",
        "/scanner",
        "/stats"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/favorites",
        "/_layout/list"
      ]
    },
    "/cart": {
      "filePath": "cart.tsx",
      "children": [
        "/cart/service"
      ]
    },
    "/colors": {
      "filePath": "colors.lazy.tsx"
    },
    "/notifications": {
      "filePath": "notifications.lazy.tsx"
    },
    "/scanner": {
      "filePath": "scanner.lazy.tsx"
    },
    "/stats": {
      "filePath": "stats.lazy.tsx"
    },
    "/_layout/favorites": {
      "filePath": "_layout/favorites.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/favorites/$favoriteId/notes"
      ]
    },
    "/_layout/list": {
      "filePath": "_layout/list.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/list/$id/details",
        "/_layout/list/$id/percents"
      ]
    },
    "/cart/service": {
      "filePath": "cart.service.tsx",
      "parent": "/cart"
    },
    "/_layout/favorites/$favoriteId/notes": {
      "filePath": "_layout/favorites.$favoriteId.notes.tsx",
      "parent": "/_layout/favorites"
    },
    "/_layout/list/$id/details": {
      "filePath": "_layout/list.$id.details.tsx",
      "parent": "/_layout/list"
    },
    "/_layout/list/$id/percents": {
      "filePath": "_layout/list.$id.percents.tsx",
      "parent": "/_layout/list"
    }
  }
}
ROUTE_MANIFEST_END */
