/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutFavoritesImport } from './routes/_layout/favorites'
import { Route as LayoutFavoritesSkuNotesImport } from './routes/_layout/favorites.$sku.notes'

// Create Virtual Routes

const ScannerLazyImport = createFileRoute('/scanner')()
const ColorsLazyImport = createFileRoute('/colors')()

// Create/Update Routes

const ScannerLazyRoute = ScannerLazyImport.update({
  path: '/scanner',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/scanner.lazy').then((d) => d.Route))

const ColorsLazyRoute = ColorsLazyImport.update({
  path: '/colors',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/colors.lazy').then((d) => d.Route))

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFavoritesRoute = LayoutFavoritesImport.update({
  path: '/favorites',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFavoritesSkuNotesRoute = LayoutFavoritesSkuNotesImport.update({
  path: '/$sku/notes',
  getParentRoute: () => LayoutFavoritesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsLazyImport
      parentRoute: typeof rootRoute
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/favorites': {
      id: '/_layout/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof LayoutFavoritesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/favorites/$sku/notes': {
      id: '/_layout/favorites/$sku/notes'
      path: '/$sku/notes'
      fullPath: '/favorites/$sku/notes'
      preLoaderRoute: typeof LayoutFavoritesSkuNotesImport
      parentRoute: typeof LayoutFavoritesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutFavoritesRoute: LayoutFavoritesRoute.addChildren({
      LayoutFavoritesSkuNotesRoute,
    }),
    LayoutIndexRoute,
  }),
  ColorsLazyRoute,
  ScannerLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/colors",
        "/scanner"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/favorites",
        "/_layout/"
      ]
    },
    "/colors": {
      "filePath": "colors.lazy.tsx"
    },
    "/scanner": {
      "filePath": "scanner.lazy.tsx"
    },
    "/_layout/favorites": {
      "filePath": "_layout/favorites.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/favorites/$sku/notes"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/favorites/$sku/notes": {
      "filePath": "_layout/favorites.$sku.notes.tsx",
      "parent": "/_layout/favorites"
    }
  }
}
ROUTE_MANIFEST_END */
